#ifndef VIRTUAL_DEVICE_GLOBAL_H
#define VIRTUAL_DEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIRTUAL_DEVICE_LIBRARY)
#  define VIRTUAL_DEVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIRTUAL_DEVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIRTUAL_DEVICE_GLOBAL_H
