#ifndef CONNING_KONGSBER_DEVICE_GLOBAL_H
#define CONNING_KONGSBER_DEVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIRTUAL_DEVICE_LIBRARY)
#  define CONNING_KONGSBER_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONNING_KONGSBER_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONNING_KONGSBER_DEVICE_GLOBAL_H
